# Generated by Django 4.1.3 on 2022-12-04 03:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('titulo_tag', models.CharField(max_length=255, verbose_name='Tag')),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cuerpo')),
                ('post_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Autor')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido de Autor')),
                ('correo', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado', models.BooleanField(default=True)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
