# Generated by Django 4.1.3 on 2022-12-09 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_alter_post_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='username',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
