# Generated by Django 4.1.3 on 2022-12-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_rename_username_autor_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='usuario',
            field=models.CharField(max_length=255, verbose_name='Nombre de usuario'),
        ),
    ]
